export default `<!DOCTYPE html><html lang="en" data-beasties-container><head>
  <meta charset="utf-8">
  <title>Wiltech</title>
  <base href="/Wiltech-Web/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<style>*{margin:0;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Open Sans,Helvetica Neue,sans-serif}
</style><link rel="stylesheet" href="styles-VAI6AAIU.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles-VAI6AAIU.css"></noscript><style ng-app-id="ng">.header[_ngcontent-ng-c2356166485]{overflow:hidden;position:sticky;background-color:#07f;top:0}.header[_ngcontent-ng-c2356166485]   a[_ngcontent-ng-c2356166485]{float:left;display:block;color:#f2f2f2;text-align:center;padding:14px 16px;text-decoration:none;font-size:17px}.header-logo[_ngcontent-ng-c2356166485]   img[_ngcontent-ng-c2356166485]{width:130px;height:auto}.header-menu[_ngcontent-ng-c2356166485]{float:right;margin-top:10px}.header-menu[_ngcontent-ng-c2356166485]   a[_ngcontent-ng-c2356166485]:hover{background-color:red;color:#000;border-radius:20px}</style><style ng-app-id="ng">.Title[_ngcontent-ng-c3771739310]{text-align:center;font-size:50px;padding:50px}.flex-container[_ngcontent-ng-c3771739310]{display:flex;flex-direction:row;font-size:30px;text-align:center}.flex-item-left[_ngcontent-ng-c3771739310]{padding:10px;flex:50%}.flex-item-left[_ngcontent-ng-c3771739310]   img[_ngcontent-ng-c3771739310]{width:300px;height:auto;border-style:inset;border-color:#000;border-radius:20px}.item-right-title[_ngcontent-ng-c3771739310]{font-size:50px;padding-bottom:20px;text-align:left}.flex-item-right[_ngcontent-ng-c3771739310]{padding:30px;flex:50%;font-size:20px;text-align:justify}@media (max-width: 800px){.flex-container[_ngcontent-ng-c3771739310]{flex-direction:column}}.flex-button[_ngcontent-ng-c3771739310]{padding:20px}.about-button[_ngcontent-ng-c3771739310]{background-color:#09f;color:#fff;border:none;border-radius:10px;display:block;align-items:center;width:150px;height:45px;font-size:15px;margin-left:auto;margin-right:auto;font-weight:bolder}.about-button[_ngcontent-ng-c3771739310]:hover{color:#000;cursor:pointer;background-color:red}</style></head>
<body><!--nghm--><script type="text/javascript" id="ng-event-dispatch-contract">(()=>{function p(t,n,r,o,e,i,f,m){return{eventType:t,event:n,targetElement:r,eic:o,timeStamp:e,eia:i,eirp:f,eiack:m}}function u(t){let n=[],r=e=>{n.push(e)};return{c:t,q:n,et:[],etc:[],d:r,h:e=>{r(p(e.type,e,e.target,t,Date.now()))}}}function s(t,n,r){for(let o=0;o<n.length;o++){let e=n[o];(r?t.etc:t.et).push(e),t.c.addEventListener(e,t.h,r)}}function c(t,n,r,o,e=window){let i=u(t);e._ejsas||(e._ejsas={}),e._ejsas[n]=i,s(i,r),s(i,o,!0)}window.__jsaction_bootstrap=c;})();
</script><script>window.__jsaction_bootstrap(document.body,"ng",["click"],[]);</script>
  <app-root ng-version="19.2.4" ngh="1" ng-server-context="ssg"><app-header _nghost-ng-c2356166485 ngh="0"><div _ngcontent-ng-c2356166485 class="header"><div _ngcontent-ng-c2356166485 class="header-logo"><a _ngcontent-ng-c2356166485 routerlink="home" href="/Wiltech-Web/home" jsaction="click:;"><img _ngcontent-ng-c2356166485 src="Wiltech-Logo.png" alt="Wiltech Logo"></a></div><div _ngcontent-ng-c2356166485 class="header-menu"><a _ngcontent-ng-c2356166485 routerlink="about" href="/Wiltech-Web/about" jsaction="click:;">About</a><a _ngcontent-ng-c2356166485 routerlink="service" href="/Wiltech-Web/service" jsaction="click:;">Services</a><a _ngcontent-ng-c2356166485 routerlink="project" href="/Wiltech-Web/project" jsaction="click:;">Projects</a><a _ngcontent-ng-c2356166485 routerlink="contact" href="/Wiltech-Web/contact" jsaction="click:;">Contact Us</a></div></div></app-header><router-outlet></router-outlet><app-about _nghost-ng-c3771739310 ngh="0"><h1 _ngcontent-ng-c3771739310 class="Title">IMAGINE IT, WE'LL CREATE IT</h1></app-about><!----><app-footer ngh="0"><p>footer works!</p></app-footer></app-root>
<script src="polyfills-FFHMD2TL.js" type="module"></script><script src="main-5VZX6MUO.js" type="module"></script>

<script id="ng-state" type="application/json">{"__nghData__":[{},{"c":{"1":[{"i":"c3771739310","r":1}]}}]}</script></body></html>`;